/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlin: String = "1.4.0"

    const val org_junit_jupiter: String = "5.6.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val com_github_kt3k_coveralls_gradle_plugin: String = "2.10.2"

    const val com_jfrog_bintray_gradle_plugin: String = "1.8.5"

    const val coveralls_gradle_plugin: String = "2.8.3"

    const val hamkrest: String = "1.7.0.3"

    /**
     * Current version: "6.6"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6"
}
